### PR TITLE
Fix build errors

### PR DESCRIPTION
**Pull request by ixiDev**
I got some errors when i run `./build.sh` so i try to fix the errors and push it.

Thanks for this library I think the future of IRIS will be great .

### CODE REVIEW

**Review by jungwonkim — COMMENTED** [review]
Hi ixiDev,

any reason to replace option with set?

**Comment by ixiDev** [comment]
> Hi ixiDev,
> 
>     1. any reason to replace option with set?
> 
>     2. all the brisbane stuffs will be replace with iris. We don't need to create include/brisbane/ directory.
> 
>     3. I've added $(IRIS)/lib $(IRIS)/lib64 in the LDFLAGS.
> 
> 
> Thank you for your contribution!
> 
> Jungwon

Hi Jungwon.

I was using cmake `v3.21.4` and when I set **USE_PYTHON** to `OFF` with `option` it's not working the state  still `ON` I try to find way  this happen so I didn't find why and I just use **set**  as a solution  to fix the problem.
Thank you.

**Comment by jungwonkim** [comment]
Got it!

**Comment by jungwonkim** [comment]
Updated the header locations.

**Pull request closed without merging**
