### PR TITLE
Update the IRIS runtime and API to support both old Brisbane API and new IRIS API

### PR DESCRIPTION
**Pull request by seyonglee**
- Update the IRIS runtime and API to support both old Brisbane API and new IRIS API.
        - Tested with OpenARC and verified that both Brisbane and IRIS APIs are correctly working for all OpenARC-generated IRIS/Brisbane applications.
        - Also tested with the example applications in this repository (./apps).

### CODE REVIEW

**Comment by seyonglee** [comment]
Please check whether these changes still work with your IRIS/Brisbane applications.
This new IRIS runtime still provides old Brisbane APIs (prefixed with brisbane_); the only two changes needed to use this new runtime is 1) to change the library name from libbrisbane to libiris, and 2) to change the include path from "brisbane/brisbane_runntime.h" to "iris/brisbane_runtime.h"

**Comment by seyonglee** [comment]
In fact, the new header file ("iris/iris_runtime.h") is already existing, but not all APIs are ported to the new IRIS header file yet. What I did in the pull request is to add missing IRIS APIs that are used by OpenARC. Please let me know if there are any missing new IRIS APIs used by your applications; I will add them too.

**Comment by BeauJoh** [comment]
Hey @seyonglee , Great work with the API. I've added the vector addition kernel and seemed good (with a simple search and replace fixed almost everything). I've introduced a higher level makefile_defs.mk to the top level of the apps directory to just clear up the environment variables in all the makefiles. Other than that, every app I tested worked fine. I'll bring in my logging changes and DAGGER next, but I think this merge request should be accepted!

**Comment by miniskar** [comment]
I observed that the public repository of IRIS doesn't have changes for XILINX support. So, I do not have any other tests other than Xilinx support tests. I have pulled the changes and reviewed the code. 
Only one comment.
1. vecadd/vecadd-m.cpp and vecadd.cpp still have brisbane calls
Rest of the changes looks good.

**Comment by BeauJoh** [comment]
Bugger, I missed that! Just fixed it.

**Pull request closed without merging**
